[font]
size = 10.0
normal = { family = "SFMono Nerd Font Mono SemiBold" }

[scrolling]
history = 10000

[window]
opacity = 1

[window.padding]
x = 7
y = 7

[colors.primary]
background = '0x000000'
foreground = '#afaaaa'
